"""端到端测试：用无头 Chromium 通过 file:// 打开 index.html，覆盖主要功能。

运行：  pip install playwright && python -m playwright install chromium
        python3 tests/test_app.py
环境变量 SHOT_DIR 可指定截图输出目录（默认 docs/screenshots，并同时生成 docs/og-image.png）。
"""
import json, os, sys, pathlib, tempfile, struct, zlib
from playwright.sync_api import sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1]
SHOT=pathlib.Path(os.environ.get('SHOT_DIR') or ROOT/'docs'/'screenshots'); SHOT.mkdir(parents=True,exist_ok=True)
MAKE_OG=not os.environ.get('SHOT_DIR')
URL=(ROOT/'index.html').as_uri()
V1=str(ROOT/'tests'/'fixtures'/'v1-export.json')
TMP=pathlib.Path(tempfile.mkdtemp(prefix='imc-test-'))
def png(w,h,rgb):
    """纯 Python 生成 PNG（带斜线条纹），避免依赖 Pillow。"""
    rows=[]
    for y in range(h):
        row=bytearray(b'\x00')
        for x in range(w): row+=bytes((255,255,255)) if (x+y)%80<3 else bytes(rgb)
        rows.append(bytes(row))
    def ch(t,d): return struct.pack('>I',len(d))+t+d+struct.pack('>I',zlib.crc32(t+d)&0xffffffff)
    return b'\x89PNG\r\n\x1a\n'+ch(b'IHDR',struct.pack('>IIBBBBB',w,h,8,2,0,0,0))+ch(b'IDAT',zlib.compress(b''.join(rows)))+ch(b'IEND',b'')
for n,w,h,c in [('GPT-Image-1_001.png',1024,1536,(200,90,60)),('Midjourney-v7_002.png',1456,816,(60,120,200))]:
    (TMP/n).write_bytes(png(w,h,c))
IM=str(TMP)+'/'
errors=[]; log=[]
def ok(c,msg):
    log.append(('PASS' if c else 'FAIL')+' '+msg)
    if not c: print('FAIL',msg)
def set_counts(pg): return pg.locator('.set-item').count()
with sync_playwright() as p:
    b=p.chromium.launch()
    ctx=b.new_context(viewport={'width':1440,'height':900},accept_downloads=True,color_scheme='dark')
    pg=ctx.new_page()
    pg.on('console',lambda m: errors.append('console.'+m.type+': '+m.text) if m.type in('error','warning') else None)
    pg.on('pageerror',lambda e: errors.append('pageerror: '+str(e)))
    pg.on('dialog',lambda d: d.accept())
    pg.goto(URL); pg.wait_for_function('window.__ready===true'); pg.wait_for_timeout(900)
    ok(pg.locator('.help .steps .step').count()==3,'first visit shows welcome/help with 3 steps')
    ok('不会上传' in pg.locator('.help').inner_text(),'welcome explains local-only storage')
    pg.screenshot(path=str(SHOT/'welcome.png'))
    pg.locator('.modal footer [data-close]').click(); pg.wait_for_timeout(200)
    ok(pg.locator('.help').count()==0,'welcome closes')
    ok(pg.locator('.sample-banner [data-act=clearSamples]').count()==1,'sample-data notice with one-click clear')
    ok(pg.locator('.side-foot a[href*="github.com/Bin0754/image-model-compare"]').count()==1,'footer GitHub link')
    ok(pg.evaluate("document.querySelector('meta[property=\"og:image\"]').content").endswith('og-image.png'),'Open Graph tags present')
    ok(pg.locator('.card').count()==6,'sample set has 6 cards')
    ok(pg.locator('.chip.hl').count()>=3,'best-value chips highlighted in grid')
    ok(pg.locator('.card .score').count()==6 and pg.locator('.card').nth(1).locator('.score .segs i').count()==10,'10-segment score in grid captions')
    ok(pg.locator('.card').nth(1).locator('.score b').inner_text()=='9','Beta shows 9/10')
    ok('≈ ¥0.29' in pg.locator('.card').nth(1).locator('.chip').first.inner_text(),'USD cost shows RMB equivalent in grid ($0.04 ≈ ¥0.29)')
    pg.mouse.move(5,5); pg.wait_for_timeout(300)
    pg.screenshot(path=str(SHOT/'grid.png'))
    if MAKE_OG:
        pg.set_viewport_size({'width':1200,'height':630}); pg.wait_for_timeout(300)
        pg.evaluate("document.querySelector('.summary').scrollIntoView()"); pg.wait_for_timeout(300)
        pg.screenshot(path=str(ROOT/'docs'/'og-image.png')); pg.set_viewport_size({'width':1440,'height':900}); pg.evaluate("document.querySelector('#main').scrollTop=0"); pg.wait_for_timeout(200)
    # prompt collapse
    box=pg.locator('.prompt-box .clampbox').first
    ok('open' not in box.get_attribute('class') and 'short' not in box.get_attribute('class'),'prompt collapsed by default with toggle')
    hc=box.locator('.clamp').evaluate('e=>[e.clientHeight,e.scrollHeight]'); ok(hc[0]<hc[1] and hc[0]<60,'collapsed prompt clipped to ~2 lines %s'%hc)
    ok(pg.locator('.prompt-box .clampbox').count()==3,'negative prompt & notes also collapsible')
    pg.locator('.prompt-box').screenshot(path=str(SHOT/'prompt-collapsed.png'))
    box.locator('.toggle').click(); pg.wait_for_timeout(300)
    ok('open' in box.get_attribute('class'),'toggle expands prompt')
    hc=box.locator('.clamp').evaluate('e=>[e.clientHeight,e.scrollHeight]'); ok(hc[0]>=hc[1]-1,'expanded shows full prompt')
    ok('收起' in box.locator('.toggle').inner_text(),'toggle label becomes 收起')
    pg.locator('.prompt-box').screenshot(path=str(SHOT/'prompt-expanded.png'))
    box.locator('.toggle').click(); pg.wait_for_timeout(200)
    ok('open' not in box.get_attribute('class'),'toggle collapses again')
    box.locator('.clamp').click(); pg.wait_for_timeout(100)
    ok('open' in box.get_attribute('class'),'clicking collapsed text also expands')
    box.locator('.toggle').click(); pg.wait_for_timeout(100)
    shorts=pg.evaluate("[...document.querySelectorAll('.prompt-box .clampbox')].map(b=>b.classList.contains('short'))")
    ok(shorts[0]==False,'long prompt shows toggle; short fields hide it %s'%shorts)
    # lightbox
    pg.locator('.thumb').nth(1).click(); pg.wait_for_selector('.lb-panel h2'); pg.wait_for_timeout(500)
    ok('Beta' in pg.locator('.lb-panel h2').inner_text(),'lightbox opens Beta')
    ok(pg.locator('.lb-panel .kv tr').count()==3,'params rendered as key-value table')
    ok(pg.locator('.lb-panel .score.lg .segs i.on').count()==9,'lightbox 10-point score')
    ok('≈ ¥0.29' in pg.locator('.lb-panel .metric').first.inner_text(),'lightbox cost shows RMB')
    txt=pg.locator('.lb-panel').inner_text(); ok('步数' not in txt and '种子' not in txt and 'Seed' not in txt,'no steps/seed in info panel')
    lbp=pg.locator('.lb-panel .clampbox').first
    ok('open' not in lbp.get_attribute('class'),'lightbox prompt collapsed')
    pg.screenshot(path=str(SHOT/'lightbox.png'))
    lbp.locator('.toggle').click(); pg.wait_for_timeout(150); ok('open' in lbp.get_attribute('class'),'lightbox prompt expands')
    lbp.locator('.toggle').click()
    pg.keyboard.press('ArrowRight'); pg.wait_for_timeout(150)
    ok('Gamma' in pg.locator('.lb-panel h2').inner_text(),'ArrowRight navigates')
    pg.locator('.lb-tools [data-z=in]').click(); pg.locator('.lb-tools [data-z=in]').click()
    ok('scale(1.5625)' in pg.locator('.lb .zoom-stage img').get_attribute('style'),'zoom in works')
    pg.locator('.lb .prev').click(); pg.wait_for_timeout(100)
    ok('Beta' in pg.locator('.lb-panel h2').inner_text(),'prev button navigates')
    pg.keyboard.press('Escape'); ok(pg.locator('.lb').count()==0,'Esc closes lightbox')
    # table
    pg.locator('[data-view=table]').click(); pg.wait_for_selector('table tbody tr'); pg.wait_for_timeout(400)
    ok(pg.locator('tbody tr').count()==6,'table has 6 rows')
    ok(pg.locator('td.hl').count()==4,'table highlights 4 best cells')
    heads=pg.locator('thead').inner_text(); ok('步数' not in heads and '种子' not in heads,'no steps/seed columns')
    ok(pg.locator('tbody tr').nth(1).locator('td.hl .score b').inner_text()=='9','best score highlighted on 10-scale')
    pg.screenshot(path=str(SHOT/'table.png'))
    pg.locator('th[data-sort=score]').click(); ok('Beta' in pg.locator('tbody tr').first.inner_text(),'sort by score (10-scale)')
    pg.locator('th[data-sort=cost]').click(); ok('Zeta' in pg.locator('tbody tr').first.inner_text(),'sort by cost puts $0 first')
    pg.fill('#rateInput','7.0'); pg.locator('#rateInput').dispatch_event('change'); pg.wait_for_timeout(100)
    ok('≈ ¥0.28' in pg.locator('tbody').inner_text(),'changing exchange rate updates RMB display')
    pg.fill('#rateInput','7.2'); pg.locator('#rateInput').dispatch_event('change')
    pg.locator('[data-view=grid]').click()
    # new set + upload
    pg.locator('#btnNewSet').click()
    pg.fill('#setForm textarea[name=prompt]','测试提示词：一位穿汉服的女孩站在樱花树下')
    pg.fill('#setForm input[name=tags]','人像, 测试')
    with pg.expect_file_chooser() as fc: pg.locator('#setSave').click()
    fc.value.set_files([IM+'GPT-Image-1_001.png',IM+'Midjourney-v7_002.png'])
    pg.wait_for_selector('#entryForm')
    ok(pg.input_value('#entryForm input[name=model]')=='GPT-Image-1','filename prefills model name')
    ok(pg.input_value('#entryForm input[name=width]')=='1024' and pg.input_value('#entryForm input[name=height]')=='1536','resolution auto-read')
    ok(pg.input_value('#entryForm select[name=currency]')=='$','USD is default currency')
    ok(pg.locator('#entryForm [name=seed],#entryForm [name=steps]').count()==0,'no seed/steps inputs in form')
    pg.fill('#entryForm input[name=provider]','OpenAI'); pg.fill('#entryForm input[name=cost]','0.17')
    ok('≈ ¥1.22' in pg.locator('#cnyLive').inner_text(),'live RMB conversion in form ($0.17 ≈ ¥1.22)')
    pg.fill('#entryForm input[name=time]','28.5'); pg.fill('#entryForm textarea[name=params]','质量: high\n尺寸: 1024x1536')
    pg.locator('#scoreIn button[data-v="8"]').click()
    ok(pg.locator('#scoreIn button.on').count()==8,'10-point score input selects 8')
    pg.locator('.modal').screenshot(path=str(SHOT/'entry-form.png'))
    pg.locator('#efSaveNext').click(); pg.wait_for_timeout(200)
    ok(pg.input_value('#entryForm input[name=model]')=='Midjourney-v7','second in queue')
    pg.fill('#entryForm input[name=cost]','0.6'); pg.fill('#entryForm input[name=time]','40')
    pg.locator('#efSave').click(); pg.wait_for_timeout(300)
    ok(pg.locator('.card').count()==2,'new set has 2 cards')
    ok(pg.locator('.card').first.locator('.score b').inner_text()=='8','saved score 8/10 shown')
    ok(set_counts(pg)==2,'sidebar shows 2 sets')
    # drag & drop
    pg.evaluate('''async()=>{const c=document.createElement('canvas');c.width=640;c.height=480;const g=c.getContext('2d');g.fillStyle='#c33';g.fillRect(0,0,640,480);
      const b=await new Promise(r=>c.toBlob(r,'image/png'));const dt=new DataTransfer();dt.items.add(new File([b],'GPT-Image-1_v2.png',{type:'image/png'}));dt.items.add(new File([b],'Flux-Pro_03.png',{type:'image/png'}));
      const m=document.querySelector('#main');m.dispatchEvent(new DragEvent('dragenter',{bubbles:true,dataTransfer:dt}));m.dispatchEvent(new DragEvent('dragover',{bubbles:true,cancelable:true,dataTransfer:dt}));m.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}));}''')
    pg.wait_for_selector('#entryForm'); pg.wait_for_timeout(200)
    ok(pg.input_value('#entryForm input[name=model]')=='GPT-Image-1','drop: model library match from filename')
    ok(pg.input_value('#entryForm input[name=provider]')=='OpenAI' and pg.input_value('#entryForm input[name=cost]')=='0.17' and pg.input_value('#entryForm select[name=currency]')=='$','model library autofill provider/cost/USD')
    ok(pg.input_value('#entryForm input[name=width]')=='640','drop: dims read')
    pg.locator('#efSaveNext').click(); pg.wait_for_timeout(200)
    ok(pg.input_value('#entryForm input[name=model]')=='Flux-Pro','second dropped file name')
    pg.locator('#entryForm input[name=best]').check(); pg.locator('#efSave').click(); pg.wait_for_timeout(300)
    ok(pg.locator('.card').count()==4,'4 cards after drop')
    ok(pg.locator('.card.is-best').count()==1,'best flag shown')
    pg.locator('.card').first.hover(); pg.locator('.card .edit').first.click(); pg.wait_for_selector('#entryForm')
    pg.fill('#entryForm textarea[name=notes]','手部细节很好'); pg.locator('#efSave').click(); pg.wait_for_timeout(150)
    # compare
    for i in range(3): pg.locator('.pick input').nth(i).check(force=True)
    pg.locator('[data-act=compare]').click(); pg.wait_for_selector('.cmp-pane'); pg.wait_for_timeout(500)
    pg.locator('.cmp .zoom-stage').first.hover(); pg.mouse.wheel(0,-400); pg.wait_for_timeout(150)
    tr=[pg.locator('.cmp .zoom-stage img').nth(i).get_attribute('style') for i in range(3)]
    ok(tr[0]==tr[1]==tr[2] and 'scale(1)' not in tr[0],'synced zoom across compare panes')
    pg.mouse.move(5,5); pg.wait_for_timeout(200); pg.screenshot(path=str(SHOT/'compare.png'))
    pg.keyboard.press('Escape')
    pg.fill('#search','汉服'); ok(set_counts(pg)==1,'search filters sets'); pg.fill('#search','')
    # model library has no steps
    pg.locator('#btnModels').click(); pg.wait_for_selector('#libBody table')
    ok('步数' not in pg.locator('#libBody').inner_text(),'model library has no steps column')
    pg.keyboard.press('Escape')
    # export
    with pg.expect_download() as dl: pg.locator('#btnExport').click()
    path='/tmp/imc_export.json'; dl.value.save_as(path)
    data=json.load(open(path))
    ok(data['version']==2,'export schema version 2')
    ok(len(data['sets'])==2 and len(data['entries'])==10 and all(e['image'].startswith('data:image') for e in data['entries']),'export JSON with embedded images')
    ok(not any('seed' in e or 'steps' in e for e in data['entries']),'export has no seed/steps')
    # wipe & re-import v2
    pg.locator('#btnModels').click(); pg.wait_for_selector('#libWipe'); pg.locator('#libWipe').click(); pg.wait_for_timeout(300)
    ok(set_counts(pg)==0,'wipe cleared all')
    with pg.expect_file_chooser() as fc: pg.locator('#btnImport').click()
    fc.value.set_files(path); pg.wait_for_timeout(800)
    ok(set_counts(pg)==2,'import v2 restored 2 sets')
    sc=pg.evaluate("S.entries.find(e=>e.model==='示例模型 Beta').score"); ok(sc==9,'v2 import keeps score (9)')
    # import old v1 export -> scores doubled
    with pg.expect_file_chooser() as fc: pg.locator('#btnImport').click()
    fc.value.set_files(V1); pg.wait_for_timeout(800)
    r=pg.evaluate("(()=>{const g=id=>S.entries.find(e=>e.id===id).score;return [g('sample-1'),g('sample-0'),g('legacy-1'),S.entries.some(e=>'seed' in e||'steps' in e),S.models.some(m=>'steps' in m)]})()")
    ok(r==[10,8,6,False,False],'v1 import: 5→10, 4→8, 3→6, seed/steps dropped %s'%r)
    # existing-DB migration (v1 database -> v2)
    pg.evaluate('''new Promise(res=>{const t=db.transaction(['entries','meta'],'readwrite');const es=t.objectStore('entries');
      const e=S.entries.find(x=>x.id==='sample-2');es.put({...e,score:3,seed:'42',steps:20});t.objectStore('meta').delete('schema');t.oncomplete=res})''')
    pg.reload(); pg.wait_for_function('window.__ready===true'); pg.wait_for_timeout(400)
    ok(pg.locator('.help').count()==0,'welcome not shown again after first visit')
    r=pg.evaluate("(()=>{const e=S.entries.find(x=>x.id==='sample-2');return [e.score,'seed' in e,'steps' in e]})()")
    ok(r==[6,False,False],'old IndexedDB migrated on load: 3→6, seed/steps removed %s'%r)
    ok(set_counts(pg)==3,'persisted after reload: 3 sets (v2 import + merged v1 import)')
    imgok=pg.evaluate('Promise.all([...document.querySelectorAll(".thumb img")].map(i=>i.decode().then(()=>i.naturalWidth>0).catch(()=>false)))')
    ok(all(imgok),'all thumbnails decode')
    # one-click clear sample data, then reload it from help
    pg.locator('.set-item[data-set="sample-set"]').click(); pg.wait_for_timeout(200)
    pg.locator('.sample-banner [data-act=clearSamples]').click(); pg.wait_for_timeout(300)
    ok(pg.locator('.set-item[data-set="sample-set"]').count()==0 and pg.evaluate("S.entries.every(e=>e.setId!=='sample-set')"),'one-click clear removes sample set + entries')
    pg.locator('#btnHelp').click(); pg.locator('#helpSample').click(); pg.wait_for_timeout(800)
    ok(pg.locator('.set-item[data-set="sample-set"]').count()==1 and pg.locator('.card').count()==6,'help panel can reload sample data')
    # light theme + mobile sanity
    pg.locator('#btnTheme').click(); pg.wait_for_timeout(300); pg.screenshot(path='/tmp/light.png')
    pg.locator('#btnTheme').click()
    pg.set_viewport_size({'width':420,'height':860}); pg.wait_for_timeout(300); pg.screenshot(path='/tmp/mobile.png')
    b.close()
print('\n'.join(log)); print('TOTAL',len(log),'PASS',sum(l.startswith('PASS') for l in log)); print('ERRORS:',errors)
sys.exit(1 if errors or any(l.startswith('FAIL') for l in log) else 0)
